import sqlalchemy as sa
from alembic import op

revision = "9acefe75478e"
down_revision = "2e68dea69861"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alert", sa.Column("amount", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alert", "amount")
    # ### end Alembic commands ###
