import sqlalchemy as sa
from alembic import op

revision = "6fc5311d95ac"
down_revision = "9acefe75478e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alert", sa.Column("triggered", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alert", "triggered")
    # ### end Alembic commands ###
