apiVersion: v1
kind: ConfigMap
metadata:
  name: coingecko-daemon-config
  namespace: default
data:
  DB_HOST: tfg-db
  DB_PORT: "5432"
  DB_NAME: tfg_db
  DB_USER: tfg_user
  DB_PASSWORD: tfg_password
  COINGECKO_API_KEY: "CG-HJ1MQ4HXvhWUz9J7aRQgbUUw"
  COINGECKO_BASE_URL: "https://api.coingecko.com/api/v3"
  COINGECKO_TIMEOUT: "10"
  HEARTBEAT_FILE: "/tmp/health-check"
  KAFKA_BOOTSTRAP_SERVERS: "redpanda.kafka.svc.cluster.local:9092"
  COINGECKO_KAFKA_TOPIC: "coingecko-prices.updates"
  CONSUMER_GROUP_ID: "tfg-consumer-group"
