version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    networks:
      - service
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      - zookeeper
    networks:
      - service
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  application:
    image: tfg
    env_file:
      - local.env
    environment:
      - PYTHONPATH=/srv/app/src
    volumes:
      - "../:/srv/app:delegated"
    networks:
      - service
    stdin_open: true
    tty: true


  daemon:
    extends:
      service: application
    networks:
      - service

  coingecko-api-daemon:
    extends:
        service: daemon
    depends_on:
      - kafka
    entrypoint: "/srv/app/scripts/coingecko_api_daemon.sh"

  shell:
    extends:
      service: application
    entrypoint: ["bash"]

  test:
    extends:
      service: application
    working_dir: /srv/app
    entrypoint: ["pytest"]
    env_file:
      - local.env

  processor-daemon:
    extends:
      service: daemon
    depends_on:
      - kafka
    entrypoint: "/srv/app/scripts/processor_daemon.sh"

  tfg-db:
    image: postgres:15-alpine
    volumes:
      - "postgres-volume:/var/lib/postgresql/data"
    env_file:
      - ./local.env
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - service

  tfg-db-shell:
    image: postgres:15-alpine
    env_file:
      - ./local.env
    entrypoint: [
      "psql",
      "-h", "tfg-db",
      "-U", "tfg_user",
      "-d", "tfg_db"
    ]
    depends_on:
      - tfg-db
    networks:
      - service
    stdin_open: true
    tty: true

  clear-tfg-db:
    image: postgres:15-alpine
    env_file:
      - ./local.env
    entrypoint: [
      "psql",
      "-h", "tfg-db",
      "-U", "tfg_user",
      "-d", "tfg_db",
      "-c", "DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;"
    ]
    depends_on:
      - tfg-db
    networks:
      - service

  alembic:
    extends:
      service: application
    entrypoint: [
      "tfg-db:5432",
      "alembic"
    ]
    depends_on:
      - tfg-db
    env_file:
      - ./local.env

volumes:
   postgres-volume:

networks:
  service: {}
