from alembic import op
import sqlalchemy as sa


revision = '1bcfb14b5743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('price_1_min_change_percent', sa.Float(), nullable=True),
    sa.Column('price_5_min_change_percent', sa.Float(), nullable=True),
    sa.Column('base_timestamp', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coin')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin')
    # ### end Alembic commands ###
