apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dummy-python-app
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: pablodt00/dummy-python-app:latest
          ports:
            - containerPort: 5000
