apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-daemon
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/target: "100"
        autoscaling.knative.dev/metric: "concurrency"
    spec:
      containers:
        - image: DOCKER_USER/tfg:latest
          ports:
            - containerPort: 7654
              protocol: TCP
          env:
            - name: PYTHONPATH
              value: /srv/src
          envFrom:
            - configMapRef:
                name: tfg-config
          command: ["/srv/scripts/api_daemon.sh"]
