apiVersion: batch/v1
kind: Job
metadata:
  name: tfg-db-migration
spec:
  template:
    spec:
      containers:
      - name: alembic
        image: pabloduranebury/tfg:latest
        command: ["alembic", "-c", "src/common/database/alembic/alembic.ini", "upgrade", "head"]
        env:
        - name: PYTHONPATH
          value: "/srv/src"
        envFrom:
        - configMapRef:
            name: tfg-config
      restartPolicy: Never
  backoffLimit: 3
