apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: coingecko-kafka-source
  namespace: default
spec:
  bootstrapServers:
    - redpanda.kafka.svc.cluster.local:9092
  topics:
    - coingecko-prices.updates
  consumerGroup: coingecko-consumer-group
  consumers: 1
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kafka-broker
