apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: redpandadata/redpanda:v23.3.3
          args:
            - redpanda
            - start
            - --overprovisioned
            - --smp
            - "1"
            - --memory
            - "512M"
            - --reserve-memory
            - "0M"
            - --node-id
            - "0"
            - --kafka-addr
            - PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr
            - PLAINTEXT://redpanda.kafka.svc.cluster.local:9092
          ports:
            - containerPort: 9092
            - containerPort: 9644
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: kafka
spec:
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: admin
      port: 9644
      targetPort: 9644
