apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: processor-trigger
  namespace: default
spec:
  broker: kafka-broker
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: processor-service
    uri: /event/
