apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webapp-daemon
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: DOCKER_USER/tfg:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PYTHONPATH
              value: /srv/src
          envFrom:
            - configMapRef:
                name: tfg-config
          command: ["/srv/scripts/webapp-daemon.sh"]
