apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: webapp-daemon
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "2"
        autoscaling.knative.dev/max-scale: "5"
        autoscaling.knative.dev/target: "20"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/scale-down-delay: "300s"
    spec:
      containerConcurrency: 20
      containers:
        - image: DOCKER_USER/tfg:latest
          ports:
            - containerPort: 8501
              protocol: TCP
          env:
            - name: PYTHONPATH
              value: /srv/src
          envFrom:
            - configMapRef:
                name: tfg-config
          command: ["/srv/scripts/webapp-daemon.sh"]
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "400m"
